sudo: required
dist: trusty

language: php

php:
  - 7.0
  - nightly

matrix:
  allow_failures:
    - php: nightly

env:
  global:
    - NO_INTERACTION=1
    - TEST_TIMEOUT=120
  matrix:
    -
    - TEST_PHP_ARGS=-m

before_install:
  - phpize && ./configure && make

install:

script:
  - sh -c "make test | tee result.txt"
  - sh test-report.sh

addons:
  apt:
    packages:
      - valgrind

#notifications:
#  email:
#    - zaq178miami@gmail.com
